- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- config/locales/simple_form.en.yml
- db/migrate/20200527135750_create_active_storage_tables.active_storage.rb
- db/schema.rb
- db/seeds.rb
> photos and seed

- app/assets/stylesheets/components/_cards_show.scss
- app/views/activities/show.html.erb
> better design

- app/assets/stylesheets/components/_banner.scss
- app/views/shared/_footer.html.erb
- app/views/users/show.html.erb
- config/routes.rb
1. changed route back to users/me
2.  user footer icon linked to my page
> changed route back to user and icon linked to my page

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_common.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/views/activities/show.html.erb
- db/seeds.rb
> fixed seed

- app/assets/stylesheets/components/_cards_show.scss
- app/controllers/activities_controller.rb
- app/controllers/players_controller.rb
- app/views/activities/show.html.erb
- config/routes.rb
join and leave work now
have the routes and the the players controller
also plugged in some notices
> Leave button

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_login.scss
- app/assets/stylesheets/pages/_signup.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
check my code form styling sign in/sign up
> forms style finished

- app/assets/stylesheets/components/_cards_show.scss
- app/views/activities/show.html.erb
have edit icon in the edit button and now space around
have delete button replaced by delete icon moved it to empty space next to title so it user more user friendly. and for show page scss changed the color to the variable
> replaced delete and added icon

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/pages/_common.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
> home page finished

- app/views/activities/index.html.erb
1. scrolling through footer (bottom)
2. 1 players needed (pluralize)
3. Capitalize first letter of activate name
4. Correct player counter in index page
> couple fixes to idx card - see notes

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_login.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/pages/home.html.erb
> buttons from login sign up page done

- app/assets/stylesheets/components/_container_edit.scss
- app/assets/stylesheets/components/_index.scss
- app/views/activities/_form.html.erb
- app/views/activities/edit.html.erb
- app/views/activities/new.html.erb
- app/views/activities/show.html.erb
changed what we discussed during stand-up
>  worked on frontend bugs

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
check the code.. homepage and activities page buttons solved
> Fixing buttons cards

- app/controllers/application_controller.rb
Check the code.. redirect after login
> after login redirect to activities page

- app/assets/stylesheets/_styles.scss
- app/assets/stylesheets/components/_cards.scss
- app/controllers/activities_controller.rb
- app/views/activities/show.html.erb
- app/views/pages/_dashboard_activities.html.erb
- app/views/pages/dashboard.html.erb
if no activities joined, created or no past, the page is not blank anymore
> general statement for dashb

- app/views/users/_current_user.html.erb
Added functioning logout button to user show page. functions properly but needs FLEX
> added basic logout button

- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_login.scss
- app/assets/stylesheets/pages/_signup.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/pages/home.html.erb
Buttons fiexed... check my code
> buttons home and forms fixed it

- app/views/activities/_card.html.erb
> routed user avatar to user show page

- app/models/user.rb
- app/views/devise/registrations/new.html.erb
check the code... username length 3 and 12 characters only
> username length 3 and 12 characters done

- app/assets/stylesheets/components/_cards.scss
- app/views/activities/_card.html.erb
> drops the host from showing as a player

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_cards_show.scss
- app/views/activities/show.html.erb
- yarn.lock
> avatar into show page

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_cards.scss
- app/views/activities/_card.html.erb
fix the avatar inside activities page, and also the line in the middle of the head :)
> fixing avatar inside the activities cards and also the line dividing

- app/views/activities/_card.html.erb
- app/views/activities/show.html.erb
- app/views/users/_current_user.html.erb
- app/views/users/_other_user.html.erb
> avatar with face detection

- app/assets/stylesheets/components/_cards_show.scss
- app/assets/stylesheets/components/_footer.scss
- app/views/activities/show.html.erb
depending on the content the show page calculates how big it should be. and no more scolling and empty white space. footbar is also sticky and not scrollable
> calculate the content of page for display

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_cards.scss
1. added height 
2. padding to bottom of description from 16px to 8px
> changed avatar height

- app/views/pages/_dashboard_activities.html.erb
activities in the dashboard order by date
> activities in dashboard order by date

- app/assets/stylesheets/components/_alert.scss
- app/javascript/packs/fade_alert.js
- app/views/shared/_flashes.html.erb
after 3.5 seconds the flashes disappear. no need to x them out. added a js pack for that and moved the alert to the top right corner
> flashes disappear alone

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_containers.scss
- app/views/users/_current_user.html.erb
there is much more things to do i think....
> Profile page some styling... there is much more to do... need suggestions

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_cards.scss
- app/views/activities/_card.html.erb
> avatar in index page align

- app/assets/stylesheets/components/_cards.scss
> Height added

- app/assets/stylesheets/components/_arrows.scss
- app/views/chatrooms/show.html.erb
- app/views/messages/_message.html.erb
username bold and local timezone correct in chatroom
> username bold and local timezone

- app/views/activities/_card.html.erb
- app/views/activities/show.html.erb
- app/views/chatrooms/index.html.erb
- app/views/chatrooms/show.html.erb
- app/views/pages/_activity_card.html.erb
- app/views/pages/test.html.erb
I left it for username.capitalize
> removed .capitalize from activitiy.title globally
